name: Metrics
on:
  schedule:
    # Runs at 12am UTC
    - cron: "0 0 * * *"
  workflow_dispatch:
  push: {branches: ["master"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - uses: lowlighter/metrics@master
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
          user: Xander1233
          use_prebuilt_image: yes
          template: classic
          config_timezone: Europe/Frankfurt
          plugin_lines: yes
          plugin_stargazers: no
          config_padding: 16, 48
          # base
          base: activity, community, repositories, metadata
          repositories_forks: no
          # habits
          plugin_habits: no
          plugin_habits_from: 1000       # Use 200 events to compute habits
          plugin_habits_days: 14        # Keep only events from last 14 days
          plugin_habits_facts: yes      # Display facts section
          plugin_habits_charts: yes     # Display charts section
          # followup
          plugin_followup: yes
          plugin_followup_sections: repositories, user
          # achievements
          plugin_achievements: no
          plugin_achievements_threshold: B       # Display achievements with rank B or higher
          plugin_achievements_secrets: yes       # Display unlocked secrets achievements
          plugin_achievements_limit: 0           # Display all unlocked achievement matching threshold and secrets params
